# Generated by Django 2.1.7 on 2019-02-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20190227_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memes',
            old_name='message',
            new_name='tittle',
        ),
        migrations.RemoveField(
            model_name='memes',
            name='name',
        ),
        migrations.AddField(
            model_name='memes',
            name='Image',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
