# Generated by Django 2.1.7 on 2019-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20190227_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='Image',
        ),
        migrations.AddField(
            model_name='memes',
            name='image',
            field=models.FileField(blank=True, upload_to=' '),
        ),
    ]
