# Generated by Django 2.1.7 on 2019-02-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_auto_20190227_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memes',
            old_name='tittle',
            new_name='title',
        ),
    ]
