# Generated by Django 2.1.7 on 2019-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_auto_20190227_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='image',
            field=models.FileField(blank=True, upload_to='media/ '),
        ),
    ]
